### ISSUE TITLE
comment-ts.documentThis

### ISSUE THREAD

**Issue by AmusedShadow** [s-albert/comment-ts#6]
It ist not possible to run your plugin.
Visual Studio presents this error Message : comment-ts.documentThis

**Comment by s-albert** [comment]
I am trying to solve the issue, but still was not successful. Any hints?

**Comment by AmusedShadow** [comment]
It seems that you have to add in 
export function activate(context: vs.ExtensionContext): void
a sheme { scheme: 'file'


 vs.languages.registerCompletionItemProvider(
      { scheme: 'file', languages },{
        provideCompletionItems:

...
see:
https://github.com/Microsoft/vscode-docs/issues/1565

**Comment by AmusedShadow** [comment]
codegen.ts

`export function generateClassesList(type: EType): IClass[] {
  let classes: IClass[] = [];
  let brackets = {
    name: null,
    within: false,
    open: 0,
    closed: 0
  };
  const currentPos = vs.window.activeTextEditor.selection.active;`

the activeTextEditor seems to be undefined.

**Comment by s-albert** [comment]
fixed with 0.9.11. It was because of an invalid vscode engines version in package.json

**Comment by AmusedShadow** [comment]
Thanks ! Great to know.

Merry Christmas :)

**Comment by s-albert** [comment]
A happy new year!

Schöne Grüße,
Albert

________________________________

**Comment by AmusedShadow** [comment]
work
